Docs/Verbali Interni/VI_2024-11-14/config/changelog_input.tex, Docs/Verbali Interni/VI_2024-11-14/content.tex
- Modificato changelog
- Correzioni varie nel contenuto
=> VI_2024-11-14 1.0.0

Docs/Generali/glossario/01_intro.tex, Docs/Generali/glossario/config/changelog_input.tex, Docs/Generali/glossario/titlepage.tex
- Aggiunta dei primi termini principali
Close #16
=> Aggiunti termini principali

Docs/Generali/norme_di_progetto/04_processi_supporto.tex, Docs/Generali/norme_di_progetto/config/changelog_input.tex, Docs/Generali/norme_di_progetto/template/package.tex, Docs/Generali/norme_di_progetto/titlepage.tex
- Redazione della sezione relativa ai processi di supporto
- Cambiato il titolo del documento che era "Piano di progetto" e aggiornato il campo Redazione
- Aggiornata la changelog
- Inserimento del package per i pedici nel file "package.tex"
close #19
=> norme_di_progetto 0.1.0

.github/workflows/pr_build_check.yml, Docs/Generali/norme_di_progetto/01_intro.tex, Docs/Generali/norme_di_progetto/02_processi_primari.tex, Docs/Generali/norme_di_progetto/03_processi_organizzativi.tex, Docs/Generali/norme_di_progetto/config/changelog_input.tex, Docs/Generali/norme_di_progetto/titlepage.tex
Subsections Progettazione e Codifica
=> Norme_di_progetto-subsections

Docs/Generali/analisi_dei_requisiti/02_use_cases.tex, Docs/Generali/analisi_dei_requisiti/config/changelog_input.tex, Docs/Generali/analisi_dei_requisiti/titlepage.tex
- Aggiunti dei nuovi comandi per auto-numerare i casi d`uso
close #78
=> Analisi dei requisiti - 78

Docs/Generali/piano_di_qualifica/01_intro.tex, Docs/Generali/piano_di_qualifica/02_qual_di_proc.tex, Docs/Generali/piano_di_qualifica/03_qual_di_prod.tex, Docs/Generali/piano_di_qualifica/config/changelog_input.tex, Docs/Generali/piano_di_qualifica/content.tex, Docs/Generali/piano_di_qualifica/template/metrics_table.tex, Docs/Generali/piano_di_qualifica/template/package.tex, Docs/Generali/piano_di_qualifica/template/proc_quality_table.tex, Docs/Generali/piano_di_qualifica/template/prod_quality_table.tex, Docs/Generali/piano_di_qualifica/titlepage.tex
- Aggiunta sezione Qualità di prodotto
- riviste sezioni precedenti
- close #48
=> Piano di qualifica - 48

Docs/Generali/norme_di_progetto/02_processi_primari.tex, Docs/Generali/norme_di_progetto/04_processi_supporto.tex, Docs/Generali/norme_di_progetto/config/changelog_input.tex, Docs/Generali/norme_di_progetto/titlepage.tex
- in processi primari aggiornato il codice dei requisiti
- aggiunta convenzione per i link
- aggiunto sezioni riguardanti le metriche e gli standard nella descrizione del documento "norme di progetto"
- stesura sezione del documento "piano di qualifica"
- aggiornato la sezione di accertamento della qualità
- aggiornata e resa meno ambigua la convenzione sul grassetto
- aggiornata sezione del piano di progetto
close #73
=> Norme di progetto - 73

Docs/Generali/norme_di_progetto/01_intro.tex, Docs/Generali/norme_di_progetto/02_processi_primari.tex, Docs/Generali/norme_di_progetto/03_processi_organizzativi.tex, Docs/Generali/norme_di_progetto/04_processi_supporto.tex, Docs/Generali/norme_di_progetto/05_metriche_qualita.tex, Docs/Generali/norme_di_progetto/config/changelog_input.tex, Docs/Generali/norme_di_progetto/titlepage.tex
- aggiunte metriche di processo
- aggiunte metriche di prodotto
- aggiunte reference alle metriche alle singole sezioni
close #82
=> Norme di progetto - 82

Docs/Generali/glossario/01_content.tex, Docs/Generali/glossario/config/changelog_input.tex, Docs/Generali/glossario/titlepage.tex
- Aggiunta vocabolo RTB e PB
close #88
=> Glossario - 88

Docs/Generali/piano_di_qualifica/04_test.tex, Docs/Generali/piano_di_qualifica/config/changelog_input.tex, Docs/Generali/piano_di_qualifica/content.tex, Docs/Generali/piano_di_qualifica/template/test_table.tex, Docs/Generali/piano_di_qualifica/titlepage.tex
Specifica dei test
- introduzione
- test di sistema
gulpease: 58
=> Piano di qualifica - 71

Docs/Generali/piano_di_qualifica/04_test.tex, Docs/Generali/piano_di_qualifica/config/changelog_input.tex, Docs/Generali/piano_di_qualifica/titlepage.tex
=> Piano di qualifica - 145

Docs/Generali/norme_di_progetto/01_intro.tex, Docs/Generali/norme_di_progetto/02_processi_primari.tex, Docs/Generali/norme_di_progetto/03_processi_supporto.tex, Docs/Generali/norme_di_progetto/04_processi_organizzativi.tex, Docs/Generali/norme_di_progetto/05_std_qualita.tex, Docs/Generali/norme_di_progetto/06_metriche_qualita.tex, Docs/Generali/norme_di_progetto/config/changelog_input.tex, Docs/Generali/norme_di_progetto/titlepage.tex
=> Norme di progetto - 133

Docs/Generali/piano_di_qualifica/01_intro.tex, Docs/Generali/piano_di_qualifica/02_qual_di_proc.tex, Docs/Generali/piano_di_qualifica/03_qual_di_prod.tex, Docs/Generali/piano_di_qualifica/04_test.tex, Docs/Generali/piano_di_qualifica/config/changelog_input.tex, Docs/Generali/piano_di_qualifica/titlepage.tex
=> Piano di qualifica - 133

Docs/Generali/analisi_dei_requisiti/01_intro.tex, Docs/Generali/analisi_dei_requisiti/02_use_cases.tex, Docs/Generali/analisi_dei_requisiti/03_requisiti.tex, Docs/Generali/analisi_dei_requisiti/config/changelog_input.tex, Docs/Generali/analisi_dei_requisiti/template/package.tex, Docs/Generali/analisi_dei_requisiti/titlepage.tex
=> Analisi dei requisiti - 133

Docs/Generali/piano_di_progetto/00_intro.tex, Docs/Generali/piano_di_progetto/01_analisi_rischi.tex, Docs/Generali/piano_di_progetto/02_modello.tex, Docs/Generali/piano_di_progetto/03_pianificazione.tex, Docs/Generali/piano_di_progetto/05_consuntivo.tex, Docs/Generali/piano_di_progetto/config/changelog_input.tex, Docs/Generali/piano_di_progetto/template/package.tex, Docs/Generali/piano_di_progetto/template/riskTable.tex, Docs/Generali/piano_di_progetto/titlepage.tex
=> Piano di progetto - 133

Docs/Generali/glossario/01_content.tex, Docs/Generali/glossario/config/changelog_input.tex, Docs/Generali/glossario/titlepage.tex
=> Glossario - 130

Docs/Generali/analisi_dei_requisiti/03_requisiti.tex, Docs/Generali/analisi_dei_requisiti/config/changelog_input.tex, Docs/Generali/analisi_dei_requisiti/titlepage.tex
Inseriti RV8, RV9, RV10
close #173
=> Analisi dei requisiti - 173

Docs/Generali/glossario/01_content.tex, Docs/Generali/glossario/config/changelog_input.tex, Docs/Generali/glossario/titlepage.tex
=> Glossario - 176

Docs/Generali/piano_di_qualifica/02_qual_di_proc.tex, Docs/Generali/piano_di_qualifica/03_qual_di_prod.tex, Docs/Generali/piano_di_qualifica/04_test.tex, Docs/Generali/piano_di_qualifica/config/changelog_input.tex, Docs/Generali/piano_di_qualifica/titlepage.tex
=> Piano di qualifica - 207

Docs/PB/Generali Interni/norme_di_progetto/01_intro.tex, Docs/PB/Generali Interni/norme_di_progetto/02_processi_primari.tex, Docs/PB/Generali Interni/norme_di_progetto/03_processi_supporto.tex, Docs/PB/Generali Interni/norme_di_progetto/04_processi_organizzativi.tex, Docs/PB/Generali Interni/norme_di_progetto/06_metriche_qualita.tex, Docs/PB/Generali Interni/norme_di_progetto/config/changelog_input.tex, Docs/PB/Generali Interni/norme_di_progetto/template/package.tex, Docs/PB/Generali Interni/norme_di_progetto/titlepage.tex
- Aggiorato il workflow/actions
- Aggiornati i branch protetti
- Aggiornate le directory
- Aggiunta una sezione relativa alla modifica della page (extra)
close #211
=> Norme di progetto - 211

Docs/PB/Generali Interni/norme_di_progetto/02_processi_primari.tex, Docs/PB/Generali Interni/norme_di_progetto/03_processi_supporto.tex, Docs/PB/Generali Interni/norme_di_progetto/config/changelog_input.tex, Docs/PB/Generali Interni/norme_di_progetto/titlepage.tex
-  Definire normative per la scrittura del codice
- Sezione su Docker in "gestione della configurazione" (extra)
close #210
=> Norme di progetto - 210

Docs/PB/Generali Esterni/specifica_tecnica/02_tecnologie.tex, Docs/PB/Generali Esterni/specifica_tecnica/config/changelog_input.tex, Docs/PB/Generali Esterni/specifica_tecnica/main.tex, Docs/PB/Generali Esterni/specifica_tecnica/template/package.tex, Docs/PB/Generali Esterni/specifica_tecnica/titlepage.tex
=> Specifica tecnica - 228

Docs/PB/Generali Esterni/analisi_dei_requisiti/03_requisiti.tex, Docs/PB/Generali Esterni/analisi_dei_requisiti/config/changelog_input.tex, Docs/PB/Generali Esterni/analisi_dei_requisiti/template/requirements.tex, Docs/PB/Generali Esterni/analisi_dei_requisiti/titlepage.tex
- Aggiunti i requisiti minimi HW
- Aggiornati i requisiti prestazionali (5k)
close #237
=> Analisi dei requisiti - 237

Docs/PB/Generali Interni/norme_di_progetto/02_processi_primari.tex, Docs/PB/Generali Interni/norme_di_progetto/config/changelog_input.tex, Docs/PB/Generali Interni/norme_di_progetto/titlepage.tex
- Aggiunta sezione relativa alla ricostruzione di delle immagini docker
close #233
=> Norme di progetto - 233

.github/workflows/build.yml, .github/workflows/pr_build_check.yml, Docs/PB/Generali Interni/glossario/01_content.tex, Docs/PB/Generali Interni/glossario/config/changelog_input.tex, Docs/PB/Generali Interni/glossario/titlepage.tex
aggiunta seguenti vocaboli : 
- Build
- Bundle
- Deploy
- Deployment
- Docker Compose
- DOM
- Hook
- Routing
- Superset
- Testing
close #227  &   #230
=> Glossario - 227 / 230

Docs/PB/Generali Interni/norme_di_progetto/03_processi_supporto.tex, Docs/PB/Generali Interni/norme_di_progetto/config/changelog_input.tex, Docs/PB/Generali Interni/norme_di_progetto/titlepage.tex
Aggiornamento sezione gestione della configurazione 
- scopo
- branching per la codifica
- pull requests per la codifica
- automazioni per la codifica
close #247
=> Norme di progetto - 247

.gitignore, Docs/PB/Generali Esterni/piano_di_qualifica/04_test.tex, Docs/PB/Generali Esterni/piano_di_qualifica/config/changelog_input.tex, Docs/PB/Generali Esterni/piano_di_qualifica/titlepage.tex
- aggiunti test di unità implementati
- close #304
=> Piano di qualifica - 304

3Dataviz/frontend/__test__/features/AppStatus/AppStatusSlice.test.ts, 3Dataviz/frontend/__test__/features/Data/DataSlice.test.ts, 3Dataviz/frontend/__test__/features/DataSource/DataSourceSlice.test.ts, 3Dataviz/frontend/__test__/features/Raycast/RaycastHitSlice.test.ts, 3Dataviz/frontend/__test__/utils/StateMockCreator.ts, 3Dataviz/frontend/__test__/utils/StatesMockCreator.ts, 3Dataviz/frontend/package.json, 3Dataviz/frontend/src/app/RootReducer.ts, 3Dataviz/frontend/src/features/AppStatus/AppSlice.ts, 3Dataviz/frontend/src/features/Data/DataSlice.ts, 3Dataviz/frontend/src/features/DataSource/DataSourceSlice.ts, 3Dataviz/frontend/src/features/Raycast/RaycastHitSlice.ts, 3Dataviz/frontend/src/features/Raycast/types/RaycastHit.ts, 3Dataviz/frontend/src/features/Raycast/types/RaycastHitState.ts
=> Frontend - 309

.gitignore, Docs/PB/Generali Interni/glossario/01_content.tex, Docs/PB/Generali Interni/glossario/config/changelog_input.tex, Docs/PB/Generali Interni/glossario/titlepage.tex
Aggiunti:
- memcached
- nestjs
- prop
- raycasting
- tooltip
- vite
- wrapper
=> Glossario - 318

3Dataviz/backend/src/modules/data-source/services/data-source.service.spec.ts, 3Dataviz/backend/src/modules/data-source/services/data-source.service.ts, 3Dataviz/backend/src/modules/data-visualization/services/data-visualization.service.spec.ts, 3Dataviz/backend/src/modules/data-visualization/services/data-visualization.service.ts, 3Dataviz/backend/src/modules/fetchers/config.ts, 3Dataviz/backend/src/modules/fetchers/factories/fetchers.factory.ts, 3Dataviz/backend/src/modules/fetchers/interfaces/base-fetcher.interface.ts, 3Dataviz/backend/src/modules/fetchers/services/base-api-fetcher.ts, 3Dataviz/backend/src/modules/fetchers/services/base-fetcher.ts, 3Dataviz/backend/src/modules/fetchers/services/currency-api-fetcher.spec.ts, 3Dataviz/backend/src/modules/fetchers/services/currency-api-fetcher.ts, 3Dataviz/backend/src/modules/fetchers/services/flights-api-fetcher.spec.ts, 3Dataviz/backend/src/modules/fetchers/services/flights-api-fetcher.ts, 3Dataviz/backend/src/modules/fetchers/services/population-api-fetcher.ts, 3Dataviz/backend/src/modules/fetchers/services/population-api.fetcher.spec.ts, 3Dataviz/backend/src/modules/fetchers/services/weather-api-fetcher.spec.ts, 3Dataviz/backend/src/modules/fetchers/services/weather-api-fetcher.ts
- change abstract BaseFetcher in interface
- add abstract BaseApiFetcher
- change test on fetchData with getDataset
close #326
=> Backend - 326

Docs/PB/Generali Esterni/bug_report/titlepage.tex
=> Bug report - hotfix

Docs/PB/Verbali Interni/VI_2025-04-14/config/changelog_input.tex
- corretto anno 2024->2025
close #354
=> VI_2025-04-14 - hotfix

.gitignore, Docs/PB/Generali Interni/norme_di_progetto/02_processi_primari.tex, Docs/PB/Generali Interni/norme_di_progetto/config/changelog_input.tex, Docs/PB/Generali Interni/norme_di_progetto/titlepage.tex
- Rivista struttura file frontend
- close #343
=> Norme di progetto - 343

Docs/PB/Verbali Interni/VI_2025-04-26/titlepage.tex
=> Hotfix - VI_2025-04-26

Docs/PB/Verbali Esterni/VE_2025-04-28/titlepage.tex
=> Hotfix - VE_2025-04-28

Docs/PB/Generali Esterni/piano_di_progetto/05_consuntivo.tex, Docs/PB/Generali Esterni/piano_di_progetto/config/PB_cost_table.tex, Docs/PB/Generali Esterni/piano_di_progetto/config/PB_member_table.tex, Docs/PB/Generali Esterni/piano_di_progetto/config/TOTAL_cost_table.tex, Docs/PB/Generali Esterni/piano_di_progetto/config/TOTAL_member_table.tex, Docs/PB/Generali Esterni/piano_di_progetto/config/changelog_input.tex, Docs/PB/Generali Esterni/piano_di_progetto/config/cost_report_plan_input_12.tex, Docs/PB/Generali Esterni/piano_di_progetto/config/member_report_plan_input_12.tex, Docs/PB/Generali Esterni/piano_di_progetto/config/remaining_Hours_12.tex, Docs/PB/Generali Esterni/piano_di_progetto/titlepage.tex
Stesura delle sezioni:
- consuntivo sprint 12
- consuntivo PB
- consuntivo di fine progetto
Close #368
=> Piano di progetto - 368

3Dataviz/frontend/src/components/UI/options/options.css, 3Dataviz/frontend/src/components/UI/ui.css
- migliorata la UI per i radio button
close #348
=> Frontend - radio button
